#!/usr/bin/env bash
# transfers a file from client to a server
expected_args=4
if [ "$#" -ne "$expected_args" ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
scp "$2" "$4"@"$3" "$5"
