#!/usr/bin/env bash
# Install and configure HAproxy on loadbalacer

sudo apt update -y
sudo apt install -y haproxy

# Backup the default HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Create a basic HAProxy configuration
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 311130-web-01 174.129.55.61:80 check
    server 311130-web-02 100.26.175.71:80 check
EOF'

# Restart HAProxy to apply the changes
sudo service haproxy restart

echo "HAProxy installed and configured. Verify the configuration in /etc/haproxy/haproxy.cfg"
