#!/usr/bin/env bash
# Displays text and handles signals

# SIGTERM handler
sigterm_handler()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit 0
}

# SIGINT handler
sigint_handler()
{
	echo "Y U no love me?!"
	exit 0
}

# SIGQUIT handler
sigquit_handler()
{
	rm /var/run/myscript.pid
	exit 0
}

# Register the signal handlers
trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'sigquit_handler' SIGQUIT

# Get pid and write it to file
pid=$$
echo "$pid" >> /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
done
