#!/usr/bin/env bash
# Displays numbers 1 to 100 with FizzBuzz for multiples of 3 and 5
x=1
while [ $x -le 100 ]
do
if ((x % 3 == 0 && x % 5 == 0 )); then
echo "FizzBuzz"
elif ((x % 3 == 0 )); then
echo "Fizz"
elif ((x % 5 == 0 )); then
echo "Buzz"
else
echo "$x"
fi
((x++))
done
