#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
x=1
while [ $x -le 10 ]
do
if [ $x -eq 4 ]; then
echo "bad luck"
((x++))
fi
if [ $x -eq 8 ]; then
echo "good luck"
((x++))
fi
echo "Best School"
((x++))
done

