#!/usr/bin/env bash
# Configures Ubuntu server with these requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i s/^127.*$// ~/hosts.new
echo 127.0.0.2 localhost >> ~/hosts.new
echo 8.8.8.8 facebook.com >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
